### ISSUE TITLE
Build failure -- too many open files

### ISSUE THREAD

**Issue by saraswat** [finos/legend-engine#949]
## Bug Report

I tried to build `legend-engine` with a fresh checkout from GitHub, following [these instructions](https://legend.finos.org/docs/getting-started/installation-guide).

During its test of `legend-engine-server` it throws an error because too many sockets are open.

Do I need to increase the limit on the number of open sockets? I checked with `ulimit`, I get back `unlimited`....?)

Note that after this `mvn install -DskipTests` did succeed, for whatever this is worth. I was able to launch the server, but get a number of failures to load classes, and subsequently get an error when I actually hit the server. Not sure if those problems are related to this problem (I suspect not), but will add tickets for them and link them in. 

I have to cut short error messages because the text is too long for this issue otherwise. I can upload a file with the entire log, if needed.
### Steps to Reproduce:

```
gh repo clone finos/legend-engine
cd engine
man install
````
 

### Expected Result:
I expect to see a successful build. 

Instead I got:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  49:09 min
[INFO] Finished at: 2022-09-18T05:21:11-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project legend-engine-server: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/vijaysaraswat/Documents/code/legend-engine/legend-engine-test-reports/surefire-reports-aggregate for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/vijaysaraswat/Documents/code/legend-engine/legend-engine-server && /Library/Java/JavaVirtualMachines/jdk-11.0.14.jdk/Contents/Home/bin/java '-javaagent:/Users/vijaysaraswat/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/Users/vijaysaraswat/Documents/code/legend-engine/legend-engine-server/target/jacoco.exec,excludes=org/finos/legend/engine/language/pure/grammar/from/antlr4/**/*' org.apache.maven.surefire.booter.ForkedBooter /Users/vijaysaraswat/Documents/code/legend-engine/legend-engine-server/target/surefire 2022-09-18T04-32-08_199-jvmRun1 surefire16215282550736567441tmp surefire_7712536291907575916478tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.finos.legend.engine.server.test.shared.PureTestHelper$PureTestCase
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/vijaysaraswat/Documents/code/legend-engine/legend-engine-server && /Library/Java/JavaVirtualMachines/jdk-11.0.14.jdk/Contents/Home/bin/java '-javaagent:/Users/vijaysaraswat/.m2/repository/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar=destfile=/Users/vijaysaraswat/Documents/code/legend-engine/legend-engine-server/target/jacoco.exec,excludes=org/finos/legend/engine/language/pure/grammar/from/antlr4/**/*' org.apache.maven.surefire.booter.ForkedBooter /Users/vijaysaraswat/Documents/code/legend-engine/legend-engine-server/target/surefire 2022-09-18T04-32-08_199-jvmRun1 surefire16215282550736567441tmp surefire_7712536291907575916478tmp
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.finos.legend.engine.server.test.shared.PureTestHelper$PureTestCase
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)

```

### Actual Result:

Over 50K lines are printed out during the `mvn install`. Here is the relevant portion:
```
STOP
[ERROR] Tests run: 55, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 79.103 s <<< FAILURE! - in org.finos.legend.engine.server.test.pureClient.executionPlan.Test_ExecutionPlan_JavaPlatform_UsingPureClient
[ERROR] toString(org.finos.legend.engine.server.test.shared.PureTestHelper$PureTestCase)  Time elapsed: 0.028 s  <<< ERROR!
Execution error at (resource:/core/pure/protocol/vX_X_X/invocations/execution.pure lines:99c73-103c1), "Unexpected error executing function with params [Anonymous_NoCounter, 127.0.0.1, 49467, null]"
	at org.finos.legend.pure.runtime.java.compiled.metadata.JavaMethodWithParamsSharedPureFunction.execute(JavaMethodWithParamsSharedPureFunction.java:83)
[run_log.txt](https://github.com/finos/legend-engine/files/9593975/run_log.txt)

	at org.finos.legend.pure.runtime.java.compiled.generation.processors.support.Pure.evaluate(Pure.java:480)
	at org.finos.legend.pure.generated.CoreGen.evaluate(CoreGen.java:60)
	at org.finos.legend.pure.generated.core_pure_executionPlan_javaPlatform_planConventions_test_testUtils$13.value(core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.java:413)
	at org.finos.legend.pure.generated.core_pure_executionPlan_javaPlatform_planConventions_test_testUtils$13.execute(core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.java:406)
	at org.finos.legend.pure.generated.core_pure_executionPlan_javaPlatform_planConventions_test_testUtils$13.execute(core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.java:402)
	at org.finos.legend.pure.runtime.java.compiled.generation.processors.support.Pure.evaluate(Pure.java:460)
	at org.finos.legend.pure.runtime.java.compiled.generation.processors.support.Pure.legendTest(Pure.java:208)
	at org.finos.legend.pure.generated.CoreGen.legendTest(CoreGen.java:45)
	at org.finos.legend.pure.generated.core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.Root_meta_pure_executionPlan_engine_java_tests_executeTests_Project_1__Extension_MANY__DebugContext_1__Boolean_1_(core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.java:398)
	at org.finos.legend.pure.generated.core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.Root_meta_pure_executionPlan_engine_java_tests_runTests_JavaExpressionTest_MANY__Extension_MANY__DebugContext_1__Boolean_1_(core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.java:298)
	at org.finos.legend.pure.generated.core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.Root_meta_pure_executionPlan_engine_java_tests_runTests_JavaExpressionTestSet_1__Boolean_1_(core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.java:176)
	at org.finos.legend.pure.generated.core_pure_executionPlan_javaPlatform_planConventions_test_stringLibraryTests.Root_meta_pure_executionPlan_engine_java_tests_toString__Boolean_1_(core_pure_executionPlan_javaPlatform_planConventions_test_stringLibraryTests.java:1417)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.finos.legend.engine.server.test.shared.PureTestHelper$PureTestCase.runTest(PureTestHelper.java:414)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.extensions.TestSetup.run(TestSetup.java:27)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.RuntimeException: Error: service call for URL: 'http://127.0.0.1:49467/api/pure/v1/execution/executePlan' failed: Too many open files
	at org.finos.legend.pure.runtime.java.shared.http.HttpRawHelper.executeRequest(HttpRawHelper.java:122)
	at org.finos.legend.pure.runtime.java.shared.http.HttpRawHelper.executeHttpService(HttpRawHelper.java:68)
	at org.finos.legend.pure.runtime.java.compiled.generation.processors.support.CompiledSupport.executeHttpRaw(CompiledSupport.java:3242)
	at org.finos.legend.pure.generated.core_pure_protocol_vX_X_X_invocations_execution.Root_meta_protocols_pure_vX_X_X_invocation_execution_execute_executePlan_String_1__String_1__Integer_1__String_1_(core_pure_protocol_vX_X_X_invocations_execution.java:750)
	at org.finos.legend.pure.generated.core_pure_protocol_vX_X_X_invocations_execution.Root_meta_protocols_pure_vX_X_X_invocation_execution_execute_executePlan_ExecutionPlan_1__String_1__Integer_1__Extension_MANY__String_1_(core_pure_protocol_vX_X_X_invocations_execution.java:745)
	at jdk.internal.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.finos.legend.pure.runtime.java.compiled.metadata.JavaMethodWithParamsSharedPureFunction.execute(JavaMethodWithParamsSharedPureFunction.java:52)
	... 41 more
Caused by: java.net.SocketException: Too many open files
	at java.base/java.net.Socket.createImpl(Socket.java:479)
	at java.base/java.net.Socket.getImpl(Socket.java:539)
	at java.base/java.net.Socket.setSoTimeout(Socket.java:1158)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:120)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.finos.legend.pure.runtime.java.shared.http.HttpRawHelper.executeRequest(HttpRawHelper.java:113)
	... 49 more

[ERROR] unitPureTests(org.finos.legend.engine.server.test.shared.PureTestHelper$PureTestCase)  Time elapsed: 0.164 s  <<< ERROR!
Execution error at (resource:/core/pure/protocol/vX_X_X/invocations/execution.pure lines:99c73-103c1), "Unexpected error executing function with params [Anonymous_NoCounter, 127.0.0.1, 49467, null]"
	at org.finos.legend.pure.runtime.java.compiled.metadata.JavaMethodWithParamsSharedPureFunction.execute(JavaMethodWithParamsSharedPureFunction.java:83)
	at org.finos.legend.pure.runtime.java.compiled.generation.processors.support.Pure.evaluate(Pure.java:480)
	at org.finos.legend.pure.generated.CoreGen.evaluate(CoreGen.java:60)
	at org.finos.legend.pure.generated.core_pure_executionPlan_javaPlatform_planConventions_test_testUtils$13.value(core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.java:413)
	at org.finos.legend.pure.generated.core_pure_executionPlan_javaPlatform_planConventions_test_testUtils$13.execute(core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.java:406)
	at org.finos.legend.pure.generated.core_pure_executionPlan_javaPlatform_planConventions_test_testUtils$13.execute(core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.java:402)
	at org.finos.legend.pure.runtime.java.compiled.generation.processors.support.Pure.evaluate(Pure.java:460)
	at org.finos.legend.pure.runtime.java.compiled.generation.processors.support.Pure.legendTest(Pure.java:208)
	at org.finos.legend.pure.generated.CoreGen.legendTest(CoreGen.java:45)
	at org.finos.legend.pure.generated.core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.Root_meta_pure_executionPlan_engine_java_tests_executeTests_Project_1__Extension_MANY__DebugContext_1__Boolean_1_(core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.java:398)
	at org.finos.legend.pure.generated.core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.Root_meta_pure_executionPlan_engine_java_tests_runTests_JavaPureTestSet_1__Extension_MANY__DebugContext_1__Boolean_1_(core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.java:385)
	at org.finos.legend.pure.generated.core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.Root_meta_pure_executionPlan_engine_java_tests_runTests_JavaPureTestSet_1__Boolean_1_(core_pure_executionPlan_javaPlatform_planConventions_test_testUtils.java:327)
	at org.finos.legend.pure.generated.core_pure_executionPlan_javaPlatform_planConventions_test_unitLibraryTests.Root_meta_pure_executionPlan_engine_java_tests_unitPureTests__Boolean_1_(core_pure_executionPlan_javaPlatform_planConventions_test_unitLibraryTests.java:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.finos.legend.engine.server.test.shared.PureTestHelper$PureTestCase.runTest(PureTestHelper.java:414)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.extensions.TestSetup.run(TestSetup.java:27)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.RuntimeException: Error: service call for URL: 'http://127.0.0.1:49467/api/pure/v1/execution/executePlan' failed: Too many open files
	at org.finos.legend.pure.runtime.java.shared.http.HttpRawHelper.executeRequest(HttpRawHelper.java:122)
	at org.finos.legend.pure.runtime.java.shared.http.HttpRawHelper.executeHttpService(HttpRawHelper.java:68)
	at org.finos.legend.pure.runtime.java.compiled.generation.processors.support.CompiledSupport.executeHttpRaw(CompiledSupport.java:3242)
	at org.finos.legend.pure.generated.core_pure_protocol_vX_X_X_invocations_execution.Root_meta_protocols_pure_vX_X_X_invocation_execution_execute_executePlan_String_1__String_1__Integer_1__String_1_(core_pure_protocol_vX_X_X_invocations_execution.java:750)
	at org.finos.legend.pure.generated.core_pure_protocol_vX_X_X_invocations_execution.Root_meta_protocols_pure_vX_X_X_invocation_execution_execute_executePlan_ExecutionPlan_1__String_1__Integer_1__Extension_MANY__String_1_(core_pure_protocol_vX_X_X_invocations_execution.java:745)
	at jdk.internal.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.finos.legend.pure.runtime.java.compiled.metadata.JavaMethodWithParamsSharedPureFunction.execute(JavaMethodWithParamsSharedPureFunction.java:52)
	... 41 more
Caused by: java.net.SocketException: Too many open files
	at java.base/java.net.Socket.createImpl(Socket.java:479)
	at java.base/java.net.Socket.getImpl(Socket.java:539)
	at java.base/java.net.Socket.setSoTimeout(Socket.java:1158)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:120)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
```

### Environment:
Building on a MacBook Pro running macOS Monterey 12.5.1, 64 GB memory, 8-core intel i9. 

Java:
```
java version "11.0.14" 2022-01-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.14+8-LTS-263)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.14+8-LTS-263, mixed mode)
```

maven:
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/vijaysaraswat/Downloads/apache-maven-3.6.3
Java version: 11.0.14, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.14.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.5.1", arch: "x86_64", family: "mac"
```

**Comment by aziemchawdhary-gs** [comment]
What does ulimit -n return for you? Does it return unlimited?

According to the man page for ulimit I think you want to specify the -n option (sorry if you have done this, its not clear if you have from your earlier comment about ulimit)

**Comment by saraswat** [comment]
Ah, right. 2560. (I forgot `ulimit` manages many limits) Running again after `ulimit -n 10000`. Could we please update documentation with this info (`macOS` users, at least, may need to raise `ulimit -n`.)

Execution has now progressed further. Now there appears to be some problem in retrieving a pom. (I should probably open another ticket.)

```
[INFO] Legend Engine - Test Reports ....................... SUCCESS [  2.652 s]
[INFO] Legend Engine - XT - Persistence - Component ....... SUCCESS [  0.259 s]
[INFO] Legend Engine - XT - Persistence - Component - Logical Plan SUCCESS [  7.670 s]
[INFO] Legend Engine - XT - Persistence - Component - Physical Plan FAILURE [  1.749 s]
```
The error message is:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project legend-engine-xt-persistence-component-physical-plan: Unable to generate classpath: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information for org.apache.maven.surefire:surefire-junit-platform:jar:2.22.2: Failed to retrieve POM for org.apache.maven.surefire:surefire-junit-platform:jar:2.22.2: Could not transfer artifact org.apache.maven.surefire:surefire-junit-platform:pom:2.22.2 from/to ossrh (https://s01.oss.sonatype.org/content/repositories/snapshots/): Transfer failed for https://s01.oss.sonatype.org/content/repositories/snapshots/org/apache/maven/surefire/surefire-junit-platform/2.22.2/surefire-junit-platform-2.22.2.pom
[ERROR]   org.apache.maven.surefire:surefire-junit-platform:jar:2.22.2
[ERROR] 
```

On hitting the url  `https://s01.oss.sonatype.org/content/repositories/snapshots/org/apache/maven/surefire/surefire-junit-platform/2.22.2/surefire-junit-platform-2.22.2.pom` in the browser I get a  404:

```
404 - Retrieval of /org/apache/maven/surefire/surefire-junit-platform/2.22.2/surefire-junit-platform-2.22.2.pom from M2Repository(id=snapshots) is forbidden by repository policy SNAPSHOT.

Retrieval of /org/apache/maven/surefire/surefire-junit-platform/2.22.2/surefire-junit-platform-2.22.2.pom from M2Repository(id=snapshots) is forbidden by repository policy SNAPSHOT.
```

Looks like something has changed in the world and our build code needs to change to adjust...?

**Comment by finos-admin** [comment]
This issue is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by finos-admin** [comment]
This issue was closed because it has been inactive for 35 days. Please re-open if this issue is still relevant.
